const integrationService = require('../services/integrationService');

class ExecutionAgent {
  constructor() {
    this.name = 'execution';
  }

  interpolate(templateStr, context) {
    if (typeof templateStr !== 'string') return templateStr;
    return templateStr.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (match, path) => {
      if (path === 'now') return new Date().toISOString();
      const parts = path.split('.');
      let val = context;
      for (const p of parts) {
        if (val && typeof val === 'object' && p in val) {
          val = val[p];
        } else {
          return match;
        }
      }
      return typeof val === 'object' ? JSON.stringify(val) : String(val);
    });
  }

  resolveConfig(config = {}, context = {}) {
    const resolved = {};
    for (const [key, value] of Object.entries(config)) {
      if (typeof value === 'string') {
        resolved[key] = this.interpolate(value, context);
      } else if (Array.isArray(value)) {
        resolved[key] = value.map((item) =>
          typeof item === 'string' ? this.interpolate(item, context) : item
        );
      } else if (typeof value === 'object' && value !== null) {
        resolved[key] = this.resolveConfig(value, context);
      } else {
        resolved[key] = value;
      }
    }
    return resolved;
  }

  async executeNode(node, context, userId) {
    const { data } = node;
    const category = data?.category || node.type || 'action';
    const provider = data?.provider;
    const action = data?.action;
    const rawConfig = data?.config || {};
    const config = this.resolveConfig(rawConfig, context);

    const startTime = Date.now();

    // 1. Trigger Category
    if (category === 'trigger') {
      return {
        nodeId: node.id,
        status: 'SUCCESS',
        output: {
          triggeredAt: new Date().toISOString(),
          type: action || 'manual',
          payload: context.initialInputs || { event: 'workflow_triggered', source: provider || 'system' },
        },
        durationMs: Date.now() - startTime,
      };
    }

    // 2. AI Category
    if (category === 'ai' || provider === 'llm') {
      let aiResult;
      const prompt = config.prompt || config.instruction || 'Analyze input context';
      if (action === 'classify') {
        aiResult = {
          classification: 'High Priority',
          confidence: 0.94,
          rationale: 'Input matches incident criteria.',
          output: 'High Priority Alert',
        };
      } else if (action === 'extract_entities') {
        aiResult = {
          vendor_name: 'Acme Cloud Services',
          total_amount: '$1,250.00',
          due_date: '2026-09-15',
          status: 'PENDING_APPROVAL',
          output: 'Invoice $1,250.00 from Acme Cloud Services',
        };
      } else {
        aiResult = {
          summary: 'Processed workflow step with AI reasoning agent.',
          keyPoints: ['Automated telemetry check passed', 'Notification dispatched'],
          output: `Summary: ${prompt.slice(0, 40)}... (Generated by Agentflow AI)`,
        };
      }

      return {
        nodeId: node.id,
        status: 'SUCCESS',
        output: aiResult,
        durationMs: Date.now() - startTime,
      };
    }

    // 3. Logic & Transformation Category
    if (category === 'logic') {
      const condition = config.condition || 'true';
      return {
        nodeId: node.id,
        status: 'SUCCESS',
        output: {
          evaluatedCondition: condition,
          branchTaken: true,
          output: 'Condition validated successfully',
        },
        durationMs: Date.now() - startTime,
      };
    }

    // 4. Third-Party Integrations
    if (category === 'integration' || ['gmail', 'slack', 'discord', 'google-sheets'].includes(provider)) {
      try {
        const result = await integrationService.executeIntegrationAction(userId, provider, action, config);
        return {
          nodeId: node.id,
          status: 'SUCCESS',
          output: result,
          durationMs: Date.now() - startTime,
        };
      } catch (err) {
        // Wrap with error code for RecoveryAgent
        err.nodeId = node.id;
        throw err;
      }
    }

    // Default Generic Action
    return {
      nodeId: node.id,
      status: 'SUCCESS',
      output: {
        message: `Executed action ${action || 'generic'} successfully`,
        nodeLabel: data?.label,
        output: `Step ${node.id} complete`,
      },
      durationMs: Date.now() - startTime,
    };
  }
}

module.exports = new ExecutionAgent();
